version: '3.8'

services:
  lakefs:
    image: treeverse/lakefs:latest
    container_name: lakefs
    ports:
      - "8000:8000"
    volumes:
      - lakefs_vol:/home
      - lakefs_confs:/etc/lakefs
    depends_on:
       lakefs_db:
          condition: service_healthy
    networks:
      - lakefs_network
      - external_network

  lakefs_db:
    image: postgres:14
    volumes:
      - lakefs_db_vol:/var/lib/postgresql/data
    environment:
      PGPORT: 5434
      POSTGRES_DB: lakefs_db
      POSTGRES_USER: lakefs_usr
      POSTGRES_PASSWORD: lakefs_pass

      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lakefs_usr -d lakefs_db"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - lakefs_network


volumes:
  lakefs_db_vol:
    driver: local
    driver_opts:
      type: none
      device: ./lake_db
      o: bind
  lakefs_vol:
    driver: local
    driver_opts:
      type: none
      device: ./lake_data
      o: bind
  lakefs_confs:
    driver: local
    driver_opts:
      type: none
      device: ./lake_confs
      o: bind


networks:
  lakefs_network:
    internal: true
  external_network:

